PRESET_COLS = [
    'play_id', 'game_id', 
    'home_team', 'away_team', 
    'posteam', 'posteam_type', 'defteam', 
    'yardline_100',
    'quarter_seconds_remaining', 'half_seconds_remaining', 'game_seconds_remaining', 
    'quarter_end', 
    'drive', 'sp', 
    'qtr', 'game_half',
    'down', 'goal_to_go', 'yrdln', 'ydstogo', 
    'ydsnet', 'play_type', 'yards_gained', 
    'shotgun', 'no_huddle', 
    'qb_dropback', 'qb_kneel', 'qb_spike', 'qb_scramble', 
    'pass_length', 'pass_location', 'air_yards', 'yards_after_catch', 
    'run_location', 'run_gap', 
    'field_goal_result', 'kick_distance', 
    'extra_point_result', 'two_point_conv_result', 
    'posteam_timeouts_remaining', 'defteam_timeouts_remaining', 
    'timeout', 'timeout_team', 
    'td_team', 'posteam_score', 'defteam_score', 'score_differential', 
    'posteam_score_post', 'defteam_score_post', 'score_differential_post', 
    'ep', 'epa', 'wp', 'def_wp', 'home_wp', 'away_wp', 'wpa', 
    'penalty', 'safety', 'interception', 
    'touchdown', 'pass_touchdown', 'rush_touchdown', 'return_touchdown', 
    'extra_point_attempt', 'two_point_attempt', 'field_goal_attempt', 'kickoff_attempt', 'punt_attempt', 
    'complete_pass', 
    'penalty_team', 'penalty_yards', 
    'season', 'drive_ended_with_score', 'away_score', 'home_score', 
    'game_stadium', 'roof', 'surface', 'weather', 'wind', 'temp', 'kicker_player_name']

def preset_cols():
    return PRESET_COLS